{
 "title": "Monotch_KPI",
 "time": { "from": "2022-12-14T00:00:00.000Z", "to": "2023-05-19T00:00:00.000Z" },
 "templating": {
  "list": [
   { "name": "Device_identifier", "query": "4063363092" },
   {
    "name": "kpi_type_code",
    "label": "kpi_type_code",
    "query": "select distinct  kpi_type_code\nFROM\n  kpi_1d\norder by \n  kpi_type_code ASC"
   },
   {
    "name": "org_identifier1",
    "label": "org_identifier",
    "query": "select distinct  org_identifier\nFROM\n  kpi_1d\norder by \n  org_identifier ASC"
   },
   {
    "name": "device_identifier1",
    "label": "device_identifier",
    "query": "select distinct device_identifier\nFROM\n  kpi_1d\nORDER BY device_identifier ASC"
   },
   {
    "name": "bucket_interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "sum kpi_alert_count based on time bucket($device_identifier1)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT time_bucket('$bucket_interval', time) as time, sum(kpi_alert_count)--,device_identifier\r\nFROM kpi_1d \r\nwhere device_identifier in ($device_identifier1) and kpi_type_code in ($kpi_type_code)  and org_identifier in ($org_identifier1)--and Device_identifier ='$Device_identifier' and time > '2022-12-15 01:00:00'\r\nGROUP BY time_bucket('$bucket_interval', time),device_identifier  --,org_identifier--,--,org_identifier--,--,\r\norder by time,device_identifier"
    }
   ]
  },
  {
   "title": "kpi_type",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT * FROM kpi_type ORDER BY code"
    }
   ]
  },
  {
   "title": "Avg of  kpi over all filters:dev:$device_identifier1, org:$org_identifier1",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT time_bucket('$bucket_interval', time) as time, avg(kpi_value_avg) as average_kpi--,org_identifier --,\r\nFROM kpi_1d \r\nwhere  device_identifier in ($device_identifier1) and kpi_type_code in ($kpi_type_code)  and org_identifier in ($org_identifier1)--and Device_identifier ='$Device_identifier' and time > '2022-12-15 01:00:00'\r\nGROUP BY time_bucket('$bucket_interval', time)--,org_identifier--,--,org_identifier--,--,\r\norder by time\r\n\r\n"
    }
   ]
  },
  {
   "title": "avg kpi type code",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "rawSql": "SELECT time_bucket('$bucket_interval', time) as time, avg(kpi_value_avg),kpi_type_code-- ,device_identifier--,\r\nFROM kpi_1d \r\nwhere  kpi_type_code in ($kpi_type_code)  and device_identifier in ($device_identifier1) and org_identifier in ($org_identifier1)--and Device_identifier ='$Device_identifier' and time > '2022-12-15 01:00:00'\r\nGROUP BY time_bucket('$bucket_interval', time),kpi_type_code--,org_identifier--,device_identifier--,\r\norder by time\r\n\r\n"
    }
   ]
  },
  {
   "title": "Avg of  kpi for each device_identifier for dev:$device_identifier1",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "repeat": "device_identifier1",
   "targets": [
    {
     "rawSql": "SELECT time_bucket('$bucket_interval', time) as time, avg(kpi_value_avg)--,max(device_identifier) as devices_identifier --,org_identifier --,\r\nFROM kpi_1d \r\nwhere  device_identifier in ($device_identifier1)-- and kpi_type_code in ($kpi_type_code)  and org_identifier in ($org_identifier)--and Device_identifier ='$Device_identifier' and time > '2022-12-15 01:00:00'\r\nGROUP BY time_bucket('$bucket_interval', time),device_identifier--,org_identifier--,--,org_identifier--,--,\r\norder by time,device_identifier\r\n\r\n"
    }
   ]
  },
  {
   "title": "Avg kpi for each  type code",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT time_bucket('$bucket_interval', time) as time, avg(kpi_value_avg),kpi_type_code-- ,device_identifier--,\r\nFROM kpi_1d \r\nwhere  kpi_type_code in ($kpi_type_code)  and device_identifier in ($device_identifier1) and org_identifier in ($org_identifier1)--and Device_identifier ='$Device_identifier' and time > '2022-12-15 01:00:00'\r\nGROUP BY time_bucket('$bucket_interval', time),kpi_type_code--,org_identifier--,device_identifier--,\r\norder by time\r\n\r\n"
    }
   ]
  },
  {
   "title": "Candlestick(OHLC) for kpi",
   "type": "candlestick",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "rawSql": "SELECT time_bucket('$bucket_interval', time) as time, min(kpi_value_min) as low, max(kpi_value_max) as high, avg(kpi_value_last) as last,avg(kpi_count) as volume\r\n--,lag(avg(kpi_value_last),1)  over (partition by time_bucket('$bucket_interval', time) order by time_bucket('$bucket_interval', time)) as first\r\nFROM kpi_1d \r\nwhere device_identifier in ($device_identifier1) and kpi_type_code in ($kpi_type_code)  and org_identifier in ($org_identifier1)\r\ngroup by time_bucket('$bucket_interval', time)--,device_identifier,kpi_type_code,org_identifier"
    }
   ]
  },
  { "title": "Dashboards", "type": "dashlist", "gridPos": { "h": 11, "w": 24, "x": 0, "y": 33 } }
 ]
}